name: Manuel Joriatti
description: une page perso pour les réunir toutes
url: "https://mjoriatti.github.io/"

theme: minima

lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
